/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kurniawan
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private static Connection conn;
    public Dashboard() {
        initComponents();
        Koneksi db = new Koneksi();
        conn = db.koneksiDB();
        getTabelHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jasaDesain = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        hargaBahanDesain = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hargaJasaDesain = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        totalBarangDesain = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cetakHistoryDesain = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        panelTotalHargaDesain = new javax.swing.JTextField();
        panelJasaDesain = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hargaBahanKomputer = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hargaJasaKomputer = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cetakHistoryDesain1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        panelTotalHargaKomputer = new javax.swing.JTextField();
        panelJasaKomputer = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jasaKomputer = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        totalBarangKomputer = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        hargaBahanPrinter = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        hargaJasaPrinter = new javax.swing.JTextField();
        jasaPrinter = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cetakHistoryDesain2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        panelTotalHargaPrinter = new javax.swing.JTextField();
        panelJasaPrinter = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        totalBarangPrinter = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        history = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        panelHistoryJasa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        panelHistoryHarga = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        panelHistoryId = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jasaDesain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desain Kaos", "Cetak Kaos" }));
        jasaDesain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jasaDesainActionPerformed(evt);
            }
        });

        jLabel1.setText("Harga Bahan");

        jLabel2.setText("Detail Jasa");

        hargaJasaDesain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaJasaDesainActionPerformed(evt);
            }
        });

        jLabel3.setText("Harga Jasa");

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        totalBarangDesain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBarangDesainActionPerformed(evt);
            }
        });

        jLabel4.setText("Total Barang");

        jLabel5.setText("Nama Jasa");

        jLabel6.setText("Total Harga");

        cetakHistoryDesain.setBackground(new java.awt.Color(102, 102, 255));
        cetakHistoryDesain.setForeground(new java.awt.Color(255, 255, 255));
        cetakHistoryDesain.setText("Simpan");
        cetakHistoryDesain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakHistoryDesainActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel7.setText("History Pembayaran");

        panelTotalHargaDesain.setEditable(false);
        panelTotalHargaDesain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelTotalHargaDesainActionPerformed(evt);
            }
        });

        panelJasaDesain.setEditable(false);
        panelJasaDesain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelJasaDesainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cetakHistoryDesain))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(panelTotalHargaDesain, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelJasaDesain, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJasaDesain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalHargaDesain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cetakHistoryDesain)
                    .addComponent(jButton4))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(hargaBahanDesain)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(hargaJasaDesain)
                    .addComponent(jasaDesain, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(totalBarangDesain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jasaDesain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(hargaBahanDesain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaJasaDesain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalBarangDesain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Desain Kaos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel8.setText("Total Barang");

        jLabel9.setText("Harga Bahan");

        jLabel10.setText("Detail Jasa");

        hargaJasaKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaJasaKomputerActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama Jasa");

        jLabel12.setText("Total Harga");

        cetakHistoryDesain1.setBackground(new java.awt.Color(102, 102, 255));
        cetakHistoryDesain1.setForeground(new java.awt.Color(255, 255, 255));
        cetakHistoryDesain1.setText("Simpan");
        cetakHistoryDesain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakHistoryDesain1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel13.setText("History Pembayaran");

        panelTotalHargaKomputer.setEditable(false);
        panelTotalHargaKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelTotalHargaKomputerActionPerformed(evt);
            }
        });

        panelJasaKomputer.setEditable(false);
        panelJasaKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelJasaKomputerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cetakHistoryDesain1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(panelTotalHargaKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelJasaKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJasaKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalHargaKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cetakHistoryDesain1)
                    .addComponent(jButton5))
                .addGap(45, 45, 45))
        );

        jLabel14.setText("Harga Jasa");

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jasaKomputer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Service Hardware", "Service Software" }));
        jasaKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jasaKomputerActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        totalBarangKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBarangKomputerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(hargaBahanKomputer)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(hargaJasaKomputer)
                    .addComponent(jasaKomputer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(totalBarangKomputer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jasaKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(hargaBahanKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaJasaKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalBarangKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Service Komputer", jPanel3);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        jLabel15.setText("Harga Bahan");

        jLabel16.setText("Harga Jasa");

        jLabel17.setText("Detail Jasa");

        jButton7.setBackground(new java.awt.Color(51, 102, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Simpan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        hargaJasaPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaJasaPrinterActionPerformed(evt);
            }
        });

        jasaPrinter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ganti Katrid", "Isi Tinta", "Ganti Roll" }));
        jasaPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jasaPrinterActionPerformed(evt);
            }
        });

        jLabel18.setText("Nama Jasa");

        jLabel19.setText("Total Harga");

        cetakHistoryDesain2.setBackground(new java.awt.Color(102, 102, 255));
        cetakHistoryDesain2.setForeground(new java.awt.Color(255, 255, 255));
        cetakHistoryDesain2.setText("Simpan");
        cetakHistoryDesain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakHistoryDesain2ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel20.setText("History Pembayaran");

        panelTotalHargaPrinter.setEditable(false);
        panelTotalHargaPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelTotalHargaPrinterActionPerformed(evt);
            }
        });

        panelJasaPrinter.setEditable(false);
        panelJasaPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelJasaPrinterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cetakHistoryDesain2))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(panelTotalHargaPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelJasaPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJasaPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalHargaPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cetakHistoryDesain2)
                    .addComponent(jButton8))
                .addGap(45, 45, 45))
        );

        jButton9.setBackground(new java.awt.Color(255, 0, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        totalBarangPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBarangPrinterActionPerformed(evt);
            }
        });

        jLabel21.setText("Total Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(hargaBahanPrinter)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(hargaJasaPrinter)
                    .addComponent(jasaPrinter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addComponent(totalBarangPrinter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jasaPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(4, 4, 4)
                        .addComponent(hargaBahanPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaJasaPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalBarangPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Service Printer", jPanel1);

        history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Jenis Jasa", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(history);

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));

        jLabel22.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Detail History Pembayaran");

        panelHistoryJasa.setEditable(false);
        panelHistoryJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelHistoryJasaActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 204, 204));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Jenis Jasa");

        panelHistoryHarga.setEditable(false);
        panelHistoryHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelHistoryHargaActionPerformed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(255, 204, 204));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Total Harga");

        jButton10.setBackground(new java.awt.Color(255, 102, 102));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        panelHistoryId.setEditable(false);
        panelHistoryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelHistoryIdActionPerformed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 204, 204));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Id Pembayaran");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelHistoryJasa)
                    .addComponent(panelHistoryHarga)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelHistoryId)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHistoryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHistoryJasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHistoryHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("History Pembayaran", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jasaDesainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jasaDesainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jasaDesainActionPerformed

    private void hargaJasaDesainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaJasaDesainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaJasaDesainActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.jasaDesain.resetKeyboardActions();
       hargaBahanDesain.setText("");
       hargaJasaDesain.setText("");
       totalBarangDesain.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void totalBarangDesainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBarangDesainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBarangDesainActionPerformed

    private void cetakHistoryDesainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakHistoryDesainActionPerformed
        String jasa = this.jasaDesain.getSelectedItem().toString();    
        String hargaBahan = hargaBahanDesain.getText();
        String hargaJasa = hargaJasaDesain.getText();
        String totalBarang = totalBarangDesain.getText();
    
    try {
        double hargaBahanValue = Double.parseDouble(hargaBahan);
        double hargaJasaValue = Double.parseDouble(hargaJasa);
        double totalBarangValue = Double.parseDouble(totalBarang);
        
        if(createPembayaran(jasa, hargaBahanValue, hargaJasaValue, totalBarangValue)) {
            JOptionPane.showMessageDialog(this, "Berhasil membuat pembayaran");  
            getTabelHistory();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Input harga barang, harga jasa, atau total barang tidak valid.");
    }
      
    }//GEN-LAST:event_cetakHistoryDesainActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       panelJasaDesain.setText("");
       panelTotalHargaDesain.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String jasaDesain = this.jasaDesain.getSelectedItem().toString();
        try{
            double hargaBahan = Double.parseDouble(hargaBahanDesain.getText());
            double hargaJasa = Double.parseDouble(hargaJasaDesain.getText());
            double totalBarang = Double.parseDouble(totalBarangDesain.getText());
            String totalHarga = "Rp."+((hargaBahan + hargaJasa) * totalBarang);
            panelJasaDesain.setText(jasaDesain);
            panelTotalHargaDesain.setText(totalHarga);   
       }catch(NumberFormatException e)
       {
             JOptionPane.showMessageDialog(this, "Inputan harus diisi angka");
       }
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panelJasaDesainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelJasaDesainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelJasaDesainActionPerformed

    private void panelTotalHargaDesainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelTotalHargaDesainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelTotalHargaDesainActionPerformed

    private void hargaJasaKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaJasaKomputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaJasaKomputerActionPerformed

    private void cetakHistoryDesain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakHistoryDesain1ActionPerformed
     String jasa = this.jasaKomputer.getSelectedItem().toString();    
        String hargaBahan = hargaBahanKomputer.getText();
        String hargaJasa = hargaJasaKomputer.getText();
        String totalBarang = totalBarangKomputer.getText();
        
    try {
        double hargaBahanValue = Double.parseDouble(hargaBahan);
        double hargaJasaValue = Double.parseDouble(hargaJasa);
        double totalBarangValue = Double.parseDouble(totalBarang);
        
        if(createPembayaran(jasa, hargaBahanValue, hargaJasaValue, totalBarangValue)) {
            JOptionPane.showMessageDialog(this, "Berhasil membuat pembayaran");  
            getTabelHistory();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Input harga barang, harga jasa, atau total barang tidak valid.");
    }
      
    }//GEN-LAST:event_cetakHistoryDesain1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       panelJasaKomputer.setText("");
       panelTotalHargaKomputer.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void panelTotalHargaKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelTotalHargaKomputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelTotalHargaKomputerActionPerformed

    private void panelJasaKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelJasaKomputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelJasaKomputerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String jasaDesain = this.jasaKomputer.getSelectedItem().toString();
            double hargaBahan = Double.parseDouble(hargaBahanKomputer.getText());
            double hargaJasa = Double.parseDouble(hargaJasaKomputer.getText());
            double totalBarang = Double.parseDouble(totalBarangKomputer.getText());
            String totalHarga = "Rp."+((hargaBahan + hargaJasa) * totalBarang);
            panelJasaKomputer.setText(jasaDesain);
            panelTotalHargaKomputer.setText(totalHarga);
        }catch(NumberFormatException e)
        {
             JOptionPane.showMessageDialog(this, "Inputan harus diisi angka");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jasaKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jasaKomputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jasaKomputerActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       hargaBahanKomputer.setText("");
       hargaJasaKomputer.setText("");
       totalBarangKomputer.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void totalBarangKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBarangKomputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBarangKomputerActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         try{
            String jasa = this.jasaPrinter.getSelectedItem().toString();
            double hargaBahan = Double.parseDouble(hargaBahanPrinter.getText());
            double hargaJasa = Double.parseDouble(hargaJasaPrinter.getText());
            double totalBarang = Double.parseDouble(totalBarangPrinter.getText());
            String totalHarga = "Rp."+((hargaBahan + hargaJasa) * totalBarang);
            panelJasaPrinter.setText(jasa);
            panelTotalHargaPrinter.setText(totalHarga);
        }catch(NumberFormatException e)
        {
             JOptionPane.showMessageDialog(this, "Inputan harus diisi angka");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void hargaJasaPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaJasaPrinterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaJasaPrinterActionPerformed

    private void jasaPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jasaPrinterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jasaPrinterActionPerformed

    private void cetakHistoryDesain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakHistoryDesain2ActionPerformed
       String jasa = this.jasaPrinter.getSelectedItem().toString();    
        String hargaBahan = hargaBahanPrinter.getText();
        String hargaJasa = hargaJasaPrinter.getText();
        String totalBarang = totalBarangPrinter.getText();
        
    try {
        double hargaBahanValue = Double.parseDouble(hargaBahan);
        double hargaJasaValue = Double.parseDouble(hargaJasa);
        double totalBarangValue = Double.parseDouble(totalBarang);
        
        if(createPembayaran(jasa, hargaBahanValue, hargaJasaValue, totalBarangValue)) {
            JOptionPane.showMessageDialog(this, "Berhasil membuat pembayaran");   
            getTabelHistory();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Input harga barang, harga jasa, atau total barang tidak valid.");
    }
      
    }//GEN-LAST:event_cetakHistoryDesain2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       panelJasaPrinter.setText("");
       panelTotalHargaPrinter.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void panelTotalHargaPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelTotalHargaPrinterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelTotalHargaPrinterActionPerformed

    private void panelJasaPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelJasaPrinterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelJasaPrinterActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       hargaBahanPrinter.setText("");
       hargaJasaPrinter.setText("");
       totalBarangPrinter.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void totalBarangPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBarangPrinterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBarangPrinterActionPerformed

    private void panelHistoryJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelHistoryJasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelHistoryJasaActionPerformed

    private void panelHistoryHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelHistoryHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelHistoryHargaActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            String id = panelHistoryId.getText();
            String query = "DELETE FROM pembayaran WHERE id=?";
            PreparedStatement smt = conn.prepareStatement(query);
            smt.setInt(1, Integer.parseInt(id));
            smt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil menghapus history pembayaran");
            getTabelHistory();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus history pembayaran");
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      
    }//GEN-LAST:event_jButton10ActionPerformed

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked
        panelHistoryId.setText(history.getValueAt(history.getSelectedRow(), 0).toString());
        panelHistoryJasa.setText(history.getValueAt(history.getSelectedRow(), 1).toString());
        panelHistoryHarga.setText(history.getValueAt(history.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_historyMouseClicked

    private void panelHistoryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelHistoryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelHistoryIdActionPerformed

    private DefaultTableModel tableModel;
   
    private void getTabelHistory()
    {
        tableModel = new DefaultTableModel();
        history.setModel(tableModel);
        tableModel.addColumn("Id Pembayaran");
        tableModel.addColumn("Jenis Jasa");
        tableModel.addColumn("Total Harga");
        tabelHistory();
    }
    
    private void tabelHistory()
    {
        try {
            Statement smt = conn.createStatement();
            String query = "SELECT * FROM pembayaran";
            ResultSet result =  smt.executeQuery(query);
            tableModel.setRowCount(0);
            
            while(result.next()){
                String col1Value = result.getString("id");
                String col2Value = result.getString("jasa");
                String col3Value = result.getString("total_harga");
                
                Object[] rowData = {col1Value,col2Value,col3Value};
                tableModel.addRow(rowData);
            }
            result.close();
            smt.close();
            conn.clearWarnings();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private boolean createPembayaran(String jasa,double hargaBahan,double hargaJasa,double totalBarang)
    {
        double totalHarga = 0;
        try {
           
            totalHarga = ( hargaBahan + hargaJasa ) * totalBarang;
            String query = "INSERT INTO pembayaran (id,jasa,total_harga) VALUES (null,?,?)";
            PreparedStatement smt = conn.prepareStatement(query);
            smt.setString(1, jasa);
            smt.setDouble(2, totalHarga);
            
            int rowsAffected = smt.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Data berhasil dimasukkan.");
            } else {
                System.out.println("Gagal memasukkan data.");
            }
            
            return true;
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Gagal membuat Pembayaran");
        }
        
       return false;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetakHistoryDesain;
    private javax.swing.JButton cetakHistoryDesain1;
    private javax.swing.JButton cetakHistoryDesain2;
    private javax.swing.JTextField hargaBahanDesain;
    private javax.swing.JTextField hargaBahanKomputer;
    private javax.swing.JTextField hargaBahanPrinter;
    private javax.swing.JTextField hargaJasaDesain;
    private javax.swing.JTextField hargaJasaKomputer;
    private javax.swing.JTextField hargaJasaPrinter;
    private javax.swing.JTable history;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jasaDesain;
    private javax.swing.JComboBox<String> jasaKomputer;
    private javax.swing.JComboBox<String> jasaPrinter;
    private javax.swing.JTextField panelHistoryHarga;
    private javax.swing.JTextField panelHistoryId;
    private javax.swing.JTextField panelHistoryJasa;
    private javax.swing.JTextField panelJasaDesain;
    private javax.swing.JTextField panelJasaKomputer;
    private javax.swing.JTextField panelJasaPrinter;
    private javax.swing.JTextField panelTotalHargaDesain;
    private javax.swing.JTextField panelTotalHargaKomputer;
    private javax.swing.JTextField panelTotalHargaPrinter;
    private javax.swing.JTextField totalBarangDesain;
    private javax.swing.JTextField totalBarangKomputer;
    private javax.swing.JTextField totalBarangPrinter;
    // End of variables declaration//GEN-END:variables
}
